# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-15 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0002_axfgoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axfgoods',
            name='marketprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='axfgoods',
            name='price',
            field=models.FloatField(),
        ),
    ]
